[package]
name = "batchelor"
version = "0.1.0"
edition = "2021"
default-run = "batchelor"

[[bin]]
name = "batchelor"
path = "src/bin/batchelor.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
glob = "0.3"
shlex = "1.3"
